### PR TITLE
Return storyId when available, /placement/elements

### PR DESCRIPTION
**Pull request by Shinsina**
Screenshot from 2023-05-18 10-25-26

### CODE REVIEW

**Comment by solocommand** [comment]
@Shinsina card/context here? Explicitly nulling a field should not be necessary

**Comment by Shinsina** [comment]
@solocommand Context is currently when utilizing https://github.com/parameter1/base-cms/blob/master/packages/marko-web-native-x/services/fetch-elements.js (used by: `marko-web-native-x-fetch-elements` https://github.com/parameter1/base-cms/blob/master/packages/marko-web-native-x/components/fetch-elements.marko) it doesn't return `storyId` for the given campaign when available. This is being done to be able to filter out the currently viewed story from a "More In" style block on the Watt sites.

Regarding the explicit nullification I was following the precedent set by other fields in this returned result (ex: https://github.com/parameter1/fortnight-graph/blob/master/src/services/campaign-delivery.js#L474), however if this isn't necessary I have no issue in removing it.

**Comment by Shinsina** [comment]
[Move "Brand Insights" into Native-X](https://trello.com/c/7ikO38U1/128-move-brand-insights-into-native-x)

**Review by solocommand — APPROVED** [review]
@Shinsina Thanks. The reason that was done was to ensure that a null value instead of an empty string would be returned for the creative text if it was somehow saved that way.

In this case, the field couldn't contain an empty string -- it's either a MongoID or nothing. The default serialization would remove `storyId` from the returned object if the value is undefined.

So, it's fine to leave it as-is, but generally speaking we don't want to return `null`s for falsy values unless there's a specific reason (such as an empty string) that we want to exclude.

**Pull request merged**
